# Form implementation generated from reading ui file '.\info.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(300, 80)
        Dialog.setMinimumSize(QtCore.QSize(300, 80))
        Dialog.setMaximumSize(QtCore.QSize(300, 80))
        self.formLayout = QtWidgets.QFormLayout(Dialog)
        self.formLayout.setObjectName("formLayout")
        self.okButton = QtWidgets.QDialogButtonBox(parent=Dialog)
        self.okButton.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.okButton.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.okButton.setObjectName("okButton")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.okButton)
        self.infolabel = QtWidgets.QLabel(parent=Dialog)
        self.infolabel.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.infolabel.setFont(font)
        self.infolabel.setObjectName("infolabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.infolabel)

        self.retranslateUi(Dialog)
        self.okButton.accepted.connect(Dialog.accept) # type: ignore
        self.okButton.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Bilgi"))
        self.infolabel.setText(_translate("Dialog", "Aradığınız kitap bulunamadı"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
